name: Flutter Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Analyze the code
      - name: Run Static Analysis
        run: flutter analyze

      # Build the Flutter web app
      - name: Build Flutter Web
        run: flutter build web
